/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocliente.core.relatorio;

import com.Hefesto.core.relatorios.objetos.FilaRelatorioObj;
import com.hefesto.hefestocliente.core.BeanEvent;
import com.hefesto.hefestocliente.core.HefInternalFrame;
import com.hefesto.hefestocliente.core.Messages;
import com.hefesto.hefestocliente.core.relatorioBean.FilaRelatorioBean;
import com.hefesto.hefestocomponentes.HFModal.HFModalEnum;
import com.hefesto.hefestocomponentes.HFModal.HFModalPainel;
import com.hefesto.hefestocomponentes.HFTable.utils.HFTableUtil;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author jr
 */
public class FilaRelatorio extends HefInternalFrame {

    private int count = 0;
    private int ID = count++;
    private int DESC = count++;
    private int DTGER = count++;
    private int STATUS = count++;
    private int LOGIN = count++;
    private int OBJ = count++;

    public FilaRelatorio() {
        initComponents();
        setmessageLabel(messageLAbel);
        FilaRelatorioBean bean = icone.getBeanInstance(FilaRelatorioBean.class);
        addBeanListner(bean);
        lookup(new BeanEvent(this, null));
        carregar(new BeanEvent(this, null));
        new HFTableUtil(listaRelatorios).colorize().hideColumn(OBJ);

    }

    /**
     * Creates new form HFCadastroTelas public HFCadastroTelas(HFTelaPrincipal
     * principalframe, HefUsu usuario) { super(principalframe, usuario); }
     *
     *
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpane = new javax.swing.JPanel();
        messageLAbel = new com.hefesto.hefestocomponentes.HFLabel.HFLabel();
        jPanel5 = new javax.swing.JPanel();
        usuariosCadastradosJp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaRelatorios = new com.hefesto.hefestocomponentes.HFTable.HFTable();

        setAutoscrolls(true);

        jpane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpaneLayout = new javax.swing.GroupLayout(jpane);
        jpane.setLayout(jpaneLayout);
        jpaneLayout.setHorizontalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLAbel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jpaneLayout.setVerticalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(messageLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usuariosCadastradosJp.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório Gerados"));

        listaRelatorios.setColunas(new String[] {"PIDR", "Titúlo", "Data Geração", "Status", "Usuário", "OBJ"});
        listaRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRelatoriosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaRelatorios);

        javax.swing.GroupLayout usuariosCadastradosJpLayout = new javax.swing.GroupLayout(usuariosCadastradosJp);
        usuariosCadastradosJp.setLayout(usuariosCadastradosJpLayout);
        usuariosCadastradosJpLayout.setHorizontalGroup(
            usuariosCadastradosJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        usuariosCadastradosJpLayout.setVerticalGroup(
            usuariosCadastradosJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosCadastradosJpLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuariosCadastradosJp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuariosCadastradosJp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hFComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFComboBox1FocusLost

    }//GEN-LAST:event_hFComboBox1FocusLost

    private void hFComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hFComboBox1ActionPerformed

    }//GEN-LAST:event_hFComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void listaRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRelatoriosMouseClicked

    }//GEN-LAST:event_listaRelatoriosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpane;
    private com.hefesto.hefestocomponentes.HFTable.HFTable listaRelatorios;
    private com.hefesto.hefestocomponentes.HFLabel.HFLabel messageLAbel;
    private javax.swing.JPanel usuariosCadastradosJp;
    // End of variables declaration//GEN-END:variables

    public void montaTabelaRelatorio(List<?> lst) {
        listaRelatorios.removeTable();
        listaRelatorios.addListRows(lst);
    }

    @Override
    public void excluir() {
        if (listaRelatorios.getSelectedRow() > -1) {
            FilaRelatorioObj obj = (FilaRelatorioObj) listaRelatorios.getValorColunaDaLinhaSelecionada(OBJ);
            new HFModalPainel(this, Messages.getMessage("remover.relatorio.question"),
                    Messages.getMessage("remover.relatorio.question2"), HFModalEnum.QUESTION_MODAL, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            excluir(new BeanEvent(FilaRelatorio.this, obj));
                        }
                    });
        }
    }

}
