/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocliente.core.componentes;

import com.Hefesto.core.entidades.HefFornecedor;
import com.Hefesto.core.entidades.HefFornecedorInfo;
import com.hefesto.hefestocliente.core.BeanEvent;
import com.hefesto.hefestocliente.core.HefInternalFrame;
import com.hefesto.hefestocliente.core.Icone;
import com.hefesto.hefestocliente.core.Messages;
import com.hefesto.hefestocliente.core.componentesBean.FornecedorPanelBean;
import com.hefesto.hefestocomponentes.HFUtils.HFFormatter;
import java.awt.Component;
import java.util.Observer;

/**
 *
 * @author flavio
 */
public class FornecedorPanel extends javax.swing.JPanel {

    private HefFornecedorInfo fornecedor;
    private HefInternalFrame frame;
    private FornecedorPanelBean bean;
    private Boolean editavel = false;

    /**
     * Creates new form FornecedorPanel
     */
    public FornecedorPanel() {
        initComponents();
        cpfCnpjFornecedor.setMascara(HFFormatter.CNPJ_MASK);
    }

    public void initilize(HefInternalFrame frame, boolean editavel) {
        this.frame = frame;
        this.editavel = editavel;
        bean = Icone.getInstance().getBeanInstance(FornecedorPanelBean.class);
        bean.lookup(new BeanEvent(frame, null));
        bean.adicionaObservador((Observer) frame);
        nomeFantFornecedor.setEnabled(editavel);
        razaoFornecedor.setEnabled(editavel);
        cpfCnpjFornecedor.setEnabled(editavel);
        idPessoaFisica.setEnabled(editavel);
        idPessoaJuridica.setEnabled(editavel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        codFornecedor = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel1 = new javax.swing.JLabel();
        razaoFornecedor = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeFantFornecedor = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        idPessoaFisica = new javax.swing.JRadioButton();
        idPessoaJuridica = new javax.swing.JRadioButton();
        cpfCnpjLabel = new javax.swing.JLabel();
        cpfCnpjFornecedor = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        codFornecedor.setMaiusculo(java.lang.Boolean.TRUE);
        codFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codFornecedorActionPerformed(evt);
            }
        });
        codFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codFornecedorFocusLost(evt);
            }
        });

        jLabel1.setText("Código:");

        razaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoFornecedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Razão Social:");

        jLabel4.setText("Nome Fantasia:");

        nomeFantFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFantFornecedorActionPerformed(evt);
            }
        });

        buttonGroup1.add(idPessoaFisica);
        idPessoaFisica.setText("Pessoa Fisica");
        idPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPessoaFisicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(idPessoaJuridica);
        idPessoaJuridica.setSelected(true);
        idPessoaJuridica.setText("Pessoa Júridica");
        idPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPessoaJuridicaActionPerformed(evt);
            }
        });

        cpfCnpjLabel.setText("CNPJ:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeFantFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfCnpjLabel)
                        .addGap(2, 2, 2)
                        .addComponent(cpfCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(codFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idPessoaFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPessoaJuridica)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(razaoFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(codFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPessoaFisica)
                    .addComponent(idPessoaJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfCnpjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeFantFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codFornecedorActionPerformed

    private void razaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoFornecedorActionPerformed

    private void nomeFantFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFantFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFantFornecedorActionPerformed

    private void idPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPessoaFisicaActionPerformed
        if (idPessoaFisica.isSelected()) {
            cpfCnpjFornecedor.setMascara(HFFormatter.CPF_MASK);
            cpfCnpjLabel.setText("CPF:");
        }
    }//GEN-LAST:event_idPessoaFisicaActionPerformed

    private void idPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPessoaJuridicaActionPerformed
        if (idPessoaJuridica.isSelected()) {
            cpfCnpjFornecedor.setMascara(HFFormatter.CNPJ_MASK);
            cpfCnpjLabel.setText("CNPJ:");
        }
    }//GEN-LAST:event_idPessoaJuridicaActionPerformed

    private void codFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codFornecedorFocusLost
        if (fornecedor == null || !editavel) {
            if (codFornecedor.valida()) {
                fornecedor = bean.buscaFornecedor(new BeanEvent(frame, codFornecedor.getText()));
            } else {
                fornecedor = new HefFornecedorInfo();
            }
            montaFornecedor(fornecedor);
        }
    }//GEN-LAST:event_codFornecedorFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField codFornecedor;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField cpfCnpjFornecedor;
    private javax.swing.JLabel cpfCnpjLabel;
    private javax.swing.JRadioButton idPessoaFisica;
    private javax.swing.JRadioButton idPessoaJuridica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField nomeFantFornecedor;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField razaoFornecedor;
    // End of variables declaration//GEN-END:variables

    public HefFornecedorInfo getFornecedor() {
        if (fornecedor.getIdfornecedor() != null) {
            fornecedor.setIdfornecedor(fornecedor.getIdfornecedor());
        } else if (fornecedor.getIdfornecedor() == null && editavel) {
            fornecedor.setIdfornecedor(new HefFornecedor());
            fornecedor.getIdfornecedor().setCodigoforncedor(codFornecedor.getText());
        } else {
            frame.throwError(new Exception(Messages.getMessage("fornecedor.erro.invalido")));
            return null;
        }

        fornecedor.setNome(razaoFornecedor.getText());
        fornecedor.setNomeFantasia(nomeFantFornecedor.getText());
        fornecedor.getIdfornecedor().setCpfCnpj(cpfCnpjFornecedor.getValorBigint());
        fornecedor.setIdpessoafisica(idPessoaFisica.isSelected());
        return fornecedor;
    }

    public void limpar() {
        frame.LimpaComponentes(new Component[]{this});
        fornecedor = null;

    }

    public void montaFornecedor(HefFornecedorInfo info) {
        this.fornecedor = info;
        if (info.getIdfornecedorInfo() != null) {
            codFornecedor.setText(info.getIdfornecedor().getCodigoforncedor());
            razaoFornecedor.setText(info.getNome());
            nomeFantFornecedor.setText(info.getNomeFantasia());
            cpfCnpjFornecedor.setValor(info.getIdfornecedor().getCpfCnpj());
            idPessoaFisica.setSelected(info.getIdpessoafisica());
            idPessoaJuridica.setSelected(!info.getIdpessoafisica());
        }
    }

}
