/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocliente.core.paineldecontrole;

import com.Hefesto.core.entidades.HefEmpresa;
import com.Hefesto.core.entidades.HefFilial;
import com.Hefesto.core.entidades.HefFilialInfo;
import com.Hefesto.core.entidades.HefLogradouro;
import com.hefesto.hefestocliente.Core.utils.MessageIcon;
import com.hefesto.hefestocliente.core.BeanEvent;
import com.hefesto.hefestocliente.core.HefInternalFrame;
import com.hefesto.hefestocliente.core.Messages;
import com.hefesto.hefestocliente.core.paineldecontroleBean.PainelDeControleFilialBean;
import com.hefesto.hefestocliente.core.paineldecontroleListner.PainelDeControleFilialListner;
import com.hefesto.hefestocomponentes.HFBaloon.HFBallonUtil;
import com.hefesto.hefestocomponentes.HFTable.utils.HFTableUtil;
import com.hefesto.hefestocomponentes.HFUtils.HFValidator;
import java.util.List;
import java.util.Observer;

/**
 *
 * @author jr
 */
public class PainelDeControleFilial extends HefInternalFrame implements Observer {

    private int count = 0;
    private int CODIGO = count++;
    private int DESCRICAO = count++;
    private int EMPRESA = count++;
    private int CEP = count++;
    private int RUA = count++;
    private int BAIRRO = count++;
    private int ATIVA = count++;
    private int OBJ = count++;

    private HefFilialInfo filialInfo;
    private HefLogradouro log;
    private PainelDeControleFilialListner listner;

    public PainelDeControleFilial() {
        initComponents();
        setmessageLabel(messageLAbel);
        PainelDeControleFilialBean bean = icone.getBeanInstance(PainelDeControleFilialBean.class);
        listner = bean;
        addBeanListner(bean);
        lookup(new BeanEvent(this, null));
        carregar(new BeanEvent(this, null));
        new HFTableUtil(listaFiliais).colorize().hideColumn(OBJ).setarCheckBox();
        filialInfo = new HefFilialInfo();

    }

    @Override
    public void postConstruct() {
        if (!icone.getUsuario().getIdperfil().getIdadministrador()) {
            empresasLabel.setVisible(false);
            idEmpresa.setVisible(false);
        }
    }

    /**
     * Creates new form HFCadastroTelas public HFCadastroTelas(HFTelaPrincipal
     * principalframe, HefUsu usuario) { super(principalframe, usuario); }
     *
     *
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filiaDesc = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        filialCod = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idFilialCancelada = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filialCidade = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        filialCNPJ = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        filialNumero = new com.hefesto.hefestocomponentes.HFNumberField.HFNumberField();
        jScrollPane1 = new javax.swing.JScrollPane();
        filialComplemento = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        filialCep = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        filialEmail = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel10 = new javax.swing.JLabel();
        filialTelefone = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        filialRua = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        filialBairro = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        empresasLabel = new javax.swing.JLabel();
        idEmpresa = new com.hefesto.hefestocomponentes.HFComboBox.HFComboBox();
        usuariosCadastradosJp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFiliais = new com.hefesto.hefestocomponentes.HFTable.HFTable();
        jpane = new javax.swing.JPanel();
        messageLAbel = new com.hefesto.hefestocomponentes.HFLabel.HFLabel();

        setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Filial"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Descrição:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Código:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("CEP:");

        filiaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filiaDescActionPerformed(evt);
            }
        });

        filialCod.setMaiusculo(java.lang.Boolean.TRUE);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Rua:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Numero:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("CNPJ:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Complemento:");

        idFilialCancelada.setSelected(true);
        idFilialCancelada.setText("Filial Ativa");
        idFilialCancelada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFilialCanceladaActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Bairro:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hefesto/hefestocliente/icones/home_20.png"))); // NOI18N
        jButton1.setToolTipText("Busca Cidade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filialCidade.setEditable(false);

        filialCNPJ.setMascara("##.###.###/####-##");
        filialCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filialCNPJActionPerformed(evt);
            }
        });

        filialNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        filialNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filialNumeroActionPerformed(evt);
            }
        });

        filialComplemento.setColumns(20);
        filialComplemento.setRows(5);
        jScrollPane1.setViewportView(filialComplemento);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("E-mail:");

        filialCep.setMascara("#####-###");
        filialCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filialCepActionPerformed(evt);
            }
        });
        filialCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                filialCepFocusLost(evt);
            }
        });

        filialEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filialEmailActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Telefone:");

        filialTelefone.setMascara("0(##)####-#####");
        filialTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filialTelefoneActionPerformed(evt);
            }
        });

        empresasLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        empresasLabel.setText("Empresa:");

        idEmpresa.setPesquisavel(java.lang.Boolean.TRUE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(filialEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filialTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                            .addComponent(filiaDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(filialRua, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filialNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(filialCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(filialCep, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filialCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(filialCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(filialBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(empresasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                            .addComponent(idFilialCancelada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filiaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filialCod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filialCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filialCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filialCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filialNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filialRua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filialBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filialEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filialTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(empresasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idFilialCancelada))
        );

        usuariosCadastradosJp.setBorder(javax.swing.BorderFactory.createTitledBorder("Filiais Cadastradas"));

        listaFiliais.setColunas(new String[] {"Código", "Descrição", "Empresa", "CEP", "Rua", "Bairro", "Ativa", "OBJ"});
        listaFiliais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFiliaisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaFiliais);

        javax.swing.GroupLayout usuariosCadastradosJpLayout = new javax.swing.GroupLayout(usuariosCadastradosJp);
        usuariosCadastradosJp.setLayout(usuariosCadastradosJpLayout);
        usuariosCadastradosJpLayout.setHorizontalGroup(
            usuariosCadastradosJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        usuariosCadastradosJpLayout.setVerticalGroup(
            usuariosCadastradosJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosCadastradosJpLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jpane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpaneLayout = new javax.swing.GroupLayout(jpane);
        jpane.setLayout(jpaneLayout);
        jpaneLayout.setHorizontalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLAbel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaneLayout.setVerticalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(messageLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuariosCadastradosJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuariosCadastradosJp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hFComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFComboBox1FocusLost

    }//GEN-LAST:event_hFComboBox1FocusLost

    private void hFComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hFComboBox1ActionPerformed

    }//GEN-LAST:event_hFComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void filiaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filiaDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filiaDescActionPerformed

    private void listaFiliaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFiliaisMouseClicked
        if (evt.getClickCount() == 2) {
            if (listaFiliais.getSelectedRow() > -1) {
                montaFilial((HefFilialInfo) listaFiliais.getValorColunaDaLinhaSelecionada(OBJ));
            }
        }
    }//GEN-LAST:event_listaFiliaisMouseClicked

    private void idFilialCanceladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFilialCanceladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFilialCanceladaActionPerformed

    private void filialCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filialCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filialCNPJActionPerformed

    private void filialNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filialNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filialNumeroActionPerformed

    private void filialCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filialCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filialCepActionPerformed

    private void filialEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filialEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filialEmailActionPerformed

    private void filialTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filialTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filialTelefoneActionPerformed

    private void filialCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filialCepFocusLost
        log = listner.buscaLogradouroCep(new BeanEvent(this, filialCep.getValorBigint()));
        if (log != null) {
            filialCidade.setText(log.getIdcidade().getSigla() + " - " + log.getDescricao());
            filialCep.setValorComZerosLPAD(log.getCep(), 8);
        } else {
            filialCidade.setText("");
            filialCep.limpar();
        }
    }//GEN-LAST:event_filialCepFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listner.buscaCep(new BeanEvent(this, null));
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel empresasLabel;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField filiaDesc;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField filialBairro;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField filialCNPJ;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField filialCep;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField filialCidade;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField filialCod;
    private javax.swing.JTextArea filialComplemento;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField filialEmail;
    private com.hefesto.hefestocomponentes.HFNumberField.HFNumberField filialNumero;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField filialRua;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField filialTelefone;
    private com.hefesto.hefestocomponentes.HFComboBox.HFComboBox idEmpresa;
    private javax.swing.JCheckBox idFilialCancelada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpane;
    private com.hefesto.hefestocomponentes.HFTable.HFTable listaFiliais;
    private com.hefesto.hefestocomponentes.HFLabel.HFLabel messageLAbel;
    private javax.swing.JPanel usuariosCadastradosJp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void novo() {
        Limpar();
    }

    @Override
    public void Limpar() {
        super.Limpar();

        filialInfo = new HefFilialInfo();
        log = null;
        carregar(new BeanEvent(this, null));
    }

    @Override
    public void salvar() {
        if (!filialCNPJ.getValorString().isEmpty()) {
            if (!HFValidator.validaCNPJ(filialCNPJ.getValorString())) {
                HFBallonUtil.showTimedBallon(filialCNPJ, Messages.getMessage("filial.cnpj.erro"), MessageIcon.ERROR.getIcon());
                return;
            }
        }
        if (filiaDesc.Valida()
                && filialCod.Valida()) {
            HefFilial filial;
            if (filialInfo.getIdfilial() == null) {
                filial = new HefFilial();
            } else {
                filial = filialInfo.getIdfilial();
            }
            filial.setDescricao(filiaDesc.getText());
            filialInfo.setIdfilial(filial);
            filialInfo.setBairro(filialBairro.getText());
            filialInfo.setCnpj(filialCNPJ.getValorBigint());
            filialInfo.setCodigo(filialCod.getText());
            filialInfo.setComplemento(filialComplemento.getText());
            filialInfo.setEmail(filialEmail.getText());
            filialInfo.setIdcancelada(!idFilialCancelada.isSelected());
            filialInfo.setNumero(filialNumero.getBigIntValor());
            filialInfo.setRua(filialRua.getText());
            filialInfo.setTelefone(filialTelefone.getValorBigint());
            filialInfo.setIdlogradouro(log);
            if (icone.getUsuario().getIdperfil().getIdadministrador()) {
                filialInfo.setIdempresa((HefEmpresa) idEmpresa.getObjetoSelecionado());
            } else {
                filialInfo.setIdempresa(listner.buscaEmpresaUsuario(new BeanEvent(this, null)));
            }
            salvar(new BeanEvent(this, filialInfo));
        }

    }

    private void montaFilial(HefFilialInfo filial) {

        this.filialInfo = filial;
        filiaDesc.setText(filial.getIdfilial().getDescricao());
        filialCod.setText(filial.getCodigo());
        filialBairro.setText(filial.getBairro());
        filialCNPJ.setValorComZerosLPAD(filial.getCnpj(), 14);
        filialCep.setValorComZerosLPAD(filial.getIdlogradouro() != null ? filial.getIdlogradouro().getCep() + "" : "0", 8);
        filialComplemento.setText(filial.getComplemento());
        filialCidade.setText(filial.getIdlogradouro() != null ? filial.getIdlogradouro().getIdcidade().getDescricao() : "");
        filialEmail.setText(filial.getEmail());
        filialNumero.setText(filial.getNumero() != null ? filial.getNumero() + "" : "");
        filialRua.setText(filial.getRua());
        filialTelefone.setValorComZerosRPAD(filial.getTelefone(), 12);
        idEmpresa.setObjetoSelecionado(filial.getIdempresa());
        idFilialCancelada.setSelected(!filial.getIdcancelada());
        log = filialInfo.getIdlogradouro();

    }

    public void montaTabelaFilial(List<?> lst) {
        listaFiliais.removeTable();
        listaFiliais.addListRows(lst);
    }

    public void montaComboEpresas(List<?> list) {
        idEmpresa.adicionarItens(list);
    }

    @Override
    public void update(java.util.Observable o, Object arg) {
        if (arg instanceof HefLogradouro) {
            log = (HefLogradouro) arg;
            filialCidade.setText(log.getIdcidade().getSigla() + " - " + log.getDescricao());
            filialCep.setValorComZerosLPAD(log.getCep(), 8);
        }
    }

}
