/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocliente.core.paineldecontrole;

import com.Hefesto.core.entidades.HefEmpresa;
import com.Hefesto.core.entidades.HefEmpresaInfo;
import com.Hefesto.core.entidades.HefLogradouro;
import com.hefesto.hefestocliente.Core.utils.MessageIcon;
import com.hefesto.hefestocliente.core.BeanEvent;
import com.hefesto.hefestocliente.core.HefInternalFrame;
import com.hefesto.hefestocliente.core.Messages;
import com.hefesto.hefestocliente.core.paineldecontroleBean.PainelDeControleEmpresaBean;
import com.hefesto.hefestocliente.core.paineldecontroleListner.PainelDeControleEmpresaListner;
import com.hefesto.hefestocomponentes.HFBaloon.HFBallonUtil;
import com.hefesto.hefestocomponentes.HFTable.utils.HFTableUtil;
import com.hefesto.hefestocomponentes.HFUtils.HFValidator;
import java.util.List;
import java.util.Observer;

/**
 *
 * @author jr
 */
public class PainelDeControleEmpresa extends HefInternalFrame implements Observer {

    private int count = 0;
    private int CODIGO = count++;
    private int DESCRICAO = count++;
    private int CEP = count++;
    private int RUA = count++;
    private int BAIRRO = count++;
    private int ATIVA = count++;
    private int OBJ = count++;

    private HefEmpresaInfo empresaInfo;
    private HefLogradouro log;
    private PainelDeControleEmpresaListner listner;

    public PainelDeControleEmpresa() {
        initComponents();
        setmessageLabel(messageLAbel);
        PainelDeControleEmpresaBean bean = icone.getBeanInstance(PainelDeControleEmpresaBean.class);
        listner = bean;
        addBeanListner(bean);
        lookup(new BeanEvent(this, null));
        carregar(new BeanEvent(this, null));
        new HFTableUtil(listaEmpresas).colorize().hideColumn(OBJ).setarCheckBox();
        empresaInfo = new HefEmpresaInfo();

    }

    /**
     * Creates new form HFCadastroTelas public HFCadastroTelas(HFTelaPrincipal
     * principalframe, HefUsu usuario) { super(principalframe, usuario); }
     *
     *
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empresaDesc = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        empresaCod = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idFilialCancelada = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        empresaCidade = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        empresaCNPJ = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        empresaNumero = new com.hefesto.hefestocomponentes.HFNumberField.HFNumberField();
        jScrollPane1 = new javax.swing.JScrollPane();
        empresaComplemento = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        empresaCep = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        empresaEmail = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel10 = new javax.swing.JLabel();
        empresaTelefone = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        empresaRua = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        empresaBairro = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        usuariosCadastradosJp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEmpresas = new com.hefesto.hefestocomponentes.HFTable.HFTable();
        jpane = new javax.swing.JPanel();
        messageLAbel = new com.hefesto.hefestocomponentes.HFLabel.HFLabel();

        setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Empresa"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Descrição:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Código:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("CEP:");

        empresaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaDescActionPerformed(evt);
            }
        });

        empresaCod.setMaiusculo(java.lang.Boolean.TRUE);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Rua:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Numero:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("CNPJ:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Complemento:");

        idFilialCancelada.setSelected(true);
        idFilialCancelada.setText("Empresa Ativa");
        idFilialCancelada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFilialCanceladaActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Bairro:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hefesto/hefestocliente/icones/home_20.png"))); // NOI18N
        jButton1.setToolTipText("Busca Cidade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        empresaCidade.setEditable(false);

        empresaCNPJ.setMascara("##.###.###/####-##");
        empresaCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaCNPJActionPerformed(evt);
            }
        });

        empresaNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        empresaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaNumeroActionPerformed(evt);
            }
        });

        empresaComplemento.setColumns(20);
        empresaComplemento.setRows(5);
        jScrollPane1.setViewportView(empresaComplemento);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("E-mail:");

        empresaCep.setMascara("#####-###");
        empresaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaCepActionPerformed(evt);
            }
        });
        empresaCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                empresaCepFocusLost(evt);
            }
        });

        empresaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaEmailActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Telefone:");

        empresaTelefone.setMascara("0(##)####-#####");
        empresaTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 653, Short.MAX_VALUE)
                        .addComponent(idFilialCancelada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(empresaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empresaTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                    .addComponent(empresaDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(empresaRua, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empresaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(empresaCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(empresaCep, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(empresaCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(empresaCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(empresaBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empresaCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(empresaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(empresaCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(empresaCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empresaRua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(empresaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(empresaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(empresaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(empresaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idFilialCancelada))
        );

        usuariosCadastradosJp.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresas Cadastradas"));

        listaEmpresas.setColunas(new String[] {"Código", "Descrição", "CEP", "Rua", "Bairro", "Ativa", "OBJ"});
        listaEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEmpresasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaEmpresas);

        javax.swing.GroupLayout usuariosCadastradosJpLayout = new javax.swing.GroupLayout(usuariosCadastradosJp);
        usuariosCadastradosJp.setLayout(usuariosCadastradosJpLayout);
        usuariosCadastradosJpLayout.setHorizontalGroup(
            usuariosCadastradosJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        usuariosCadastradosJpLayout.setVerticalGroup(
            usuariosCadastradosJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosCadastradosJpLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jpane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpaneLayout = new javax.swing.GroupLayout(jpane);
        jpane.setLayout(jpaneLayout);
        jpaneLayout.setHorizontalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLAbel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaneLayout.setVerticalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(messageLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuariosCadastradosJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuariosCadastradosJp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hFComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFComboBox1FocusLost

    }//GEN-LAST:event_hFComboBox1FocusLost

    private void hFComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hFComboBox1ActionPerformed

    }//GEN-LAST:event_hFComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void empresaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaDescActionPerformed

    private void listaEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEmpresasMouseClicked
        if (evt.getClickCount() == 2) {
            if (listaEmpresas.getSelectedRow() > -1) {
                montaFilial((HefEmpresaInfo) listaEmpresas.getValorColunaDaLinhaSelecionada(OBJ));
            }
        }
    }//GEN-LAST:event_listaEmpresasMouseClicked

    private void idFilialCanceladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFilialCanceladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFilialCanceladaActionPerformed

    private void empresaCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaCNPJActionPerformed

    private void empresaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaNumeroActionPerformed

    private void empresaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaCepActionPerformed

    private void empresaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaEmailActionPerformed

    private void empresaTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaTelefoneActionPerformed

    private void empresaCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empresaCepFocusLost
        log = listner.buscaLogradouroCep(new BeanEvent(this, empresaCep.getValorBigint()));
        if (log != null) {
            empresaCidade.setText(log.getIdcidade().getSigla() + " - " + log.getDescricao());
            empresaCep.setValorComZerosLPAD(log.getCep(), 8);
        } else {
            empresaCidade.setText("");
            empresaCep.limpar();
        }
    }//GEN-LAST:event_empresaCepFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listner.buscaCep(new BeanEvent(this, null));
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField empresaBairro;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField empresaCNPJ;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField empresaCep;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField empresaCidade;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField empresaCod;
    private javax.swing.JTextArea empresaComplemento;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField empresaDesc;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField empresaEmail;
    private com.hefesto.hefestocomponentes.HFNumberField.HFNumberField empresaNumero;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField empresaRua;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField empresaTelefone;
    private javax.swing.JCheckBox idFilialCancelada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpane;
    private com.hefesto.hefestocomponentes.HFTable.HFTable listaEmpresas;
    private com.hefesto.hefestocomponentes.HFLabel.HFLabel messageLAbel;
    private javax.swing.JPanel usuariosCadastradosJp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void novo() {
        Limpar();
    }

    @Override
    public void Limpar() {
        super.Limpar();

        empresaInfo = new HefEmpresaInfo();
        log = null;
        carregar(new BeanEvent(this, null));
    }

    @Override
    public void salvar() {
        if (!empresaCNPJ.getValorString().isEmpty()) {
            if (!HFValidator.validaCNPJ(empresaCNPJ.getValorString())) {
                HFBallonUtil.showTimedBallon(empresaCNPJ, Messages.getMessage("empresa.cnpj.erro"), MessageIcon.ERROR.getIcon());
                return;
            }
        }
        if (empresaDesc.Valida()
                && empresaCod.Valida()) {
            HefEmpresa empresa;
            if (empresaInfo.getIdempresa() == null) {
                empresa = new HefEmpresa();
            } else {
                empresa = empresaInfo.getIdempresa();
            }
            empresa.setDescricao(empresaDesc.getText());
            empresaInfo.setIdempresa(empresa);
            empresaInfo.setBairro(empresaBairro.getText());
            empresaInfo.setCnpj(empresaCNPJ.getValorBigint());
            empresaInfo.setCodigo(empresaCod.getText());
            empresaInfo.setComplemento(empresaComplemento.getText());
            empresaInfo.setEmail(empresaEmail.getText());
            empresaInfo.setIdcancelada(!idFilialCancelada.isSelected());
            empresaInfo.setNumero(empresaNumero.getBigIntValor());
            empresaInfo.setRua(empresaRua.getText());
            empresaInfo.setTelefone(empresaTelefone.getValorBigint());
            empresaInfo.setIdlogradouro(log);
            salvar(new BeanEvent(this, empresaInfo));
        }

    }

    private void montaFilial(HefEmpresaInfo empresaInfo) {

        this.empresaInfo = empresaInfo;
        empresaDesc.setText(empresaInfo.getIdempresa().getDescricao());
        empresaCod.setText(empresaInfo.getCodigo());
        empresaBairro.setText(empresaInfo.getBairro());
        empresaCNPJ.setValorComZerosLPAD(empresaInfo.getCnpj(), 14);
        empresaCep.setValorComZerosLPAD(empresaInfo.getIdlogradouro() != null ? empresaInfo.getIdlogradouro().getCep() + "" : "0", 8);
        empresaComplemento.setText(empresaInfo.getComplemento());
        empresaCidade.setText(empresaInfo.getIdlogradouro() != null ? empresaInfo.getIdlogradouro().getIdcidade().getDescricao() : "");
        empresaEmail.setText(empresaInfo.getEmail());
        empresaNumero.setText(empresaInfo.getNumero() != null ? empresaInfo.getNumero() + "" : "");
        empresaRua.setText(empresaInfo.getRua());
        empresaTelefone.setValorComZerosRPAD(empresaInfo.getTelefone(), 12);
        idFilialCancelada.setSelected(!empresaInfo.getIdcancelada());
        log = empresaInfo.getIdlogradouro();

    }

    public void montaTabelaEmpresa(List<?> lst) {
        listaEmpresas.removeTable();
        listaEmpresas.addListRows(lst);
    }

    @Override
    public void update(java.util.Observable o, Object arg) {
        if (arg instanceof HefLogradouro) {
            log = (HefLogradouro) arg;
            empresaCidade.setText(log.getIdcidade().getSigla() + " - " + log.getDescricao());
            empresaCep.setValorComZerosLPAD(log.getCep(), 8);
        }
    }

}
