/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocliente.cadastros.fornecedor;

import com.Hefesto.core.entidades.HefEmpresa;
import com.Hefesto.core.entidades.HefFornecedorInfo;
import com.Hefesto.core.entidades.HefLogradouro;
import com.hefesto.hefestocliente.cadastros.fornecedorBean.CadastroFornecedorBean;
import com.hefesto.hefestocliente.cadastros.fornecedorListner.CadastroFornecedorListner;
import com.hefesto.hefestocliente.core.BeanEvent;
import com.hefesto.hefestocliente.core.HefInternalFrame;
import com.hefesto.hefestocomponentes.HFTable.utils.HFTableUtil;
import java.util.List;
import java.util.Observer;

/**
 *
 * @author jr
 */
public class CadastroFornecedor extends HefInternalFrame implements Observer {

    private int count = 0;
    private int CODIGO = count++;
    private int RAZAOSOCIAL = count++;
    private int NOMEFANTASIA = count++;
    private int CNPJ = count++;
    private int OBJ = count++;
    private CadastroFornecedorListner listner;
    private HefLogradouro log;

    public CadastroFornecedor() {
        initComponents();
        setmessageLabel(messageLAbel);
        fornecedorPanel1.initilize(this, false);
        CadastroFornecedorBean bean = icone.getBeanInstance(CadastroFornecedorBean.class);
        listner = bean;
        addBeanListner(bean);
        lookup(new BeanEvent(this, null));
        carregar(new BeanEvent(this, null));
        new HFTableUtil(listaFornecedores).colorize().hideColumn(OBJ);

    }

    /**
     * Creates new form HFCadastroTelas public HFCadastroTelas(HFTelaPrincipal
     * principalframe, HefUsu usuario) { super(principalframe, usuario); }
     *
     *
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fornecedorPanel1 = new com.hefesto.hefestocliente.core.componentes.FornecedorPanel();
        tabPainel = new javax.swing.JTabbedPane();
        fornecedoresCadastradosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFornecedores = new com.hefesto.hefestocomponentes.HFTable.HFTable();
        infCompPainel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        email = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        bairro = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        rua = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        cep = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        jButton1 = new javax.swing.JButton();
        cidade = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel5 = new javax.swing.JLabel();
        numero = new com.hefesto.hefestocomponentes.HFNumberField.HFNumberField();
        jLabel10 = new javax.swing.JLabel();
        telefone = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        complemento = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel11 = new javax.swing.JLabel();
        rg = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        celular = new com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        site = new com.hefesto.hefestocomponentes.HFTextField.HFTextField();
        jLabel6 = new javax.swing.JLabel();
        empresa = new com.hefesto.hefestocomponentes.HFComboBox.HFComboBox();
        jpane = new javax.swing.JPanel();
        messageLAbel = new com.hefesto.hefestocomponentes.HFLabel.HFLabel();

        setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Empresa"));

        fornecedoresCadastradosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresas Cadastradas"));

        listaFornecedores.setColunas(new String[] {"Código", "Razão Social", "Nome Fantasia", "CNPJ", "OBJ"});
        listaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaFornecedores);

        javax.swing.GroupLayout fornecedoresCadastradosPanelLayout = new javax.swing.GroupLayout(fornecedoresCadastradosPanel);
        fornecedoresCadastradosPanel.setLayout(fornecedoresCadastradosPanelLayout);
        fornecedoresCadastradosPanelLayout.setHorizontalGroup(
            fornecedoresCadastradosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );
        fornecedoresCadastradosPanelLayout.setVerticalGroup(
            fornecedoresCadastradosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fornecedoresCadastradosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        tabPainel.addTab("Fornecedores Cadastrados", fornecedoresCadastradosPanel);

        infCompPainel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Complemento:");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        cep.setMascara("#####-###");
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        cep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cepFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hefesto/hefestocliente/icones/home_20.png"))); // NOI18N
        jButton1.setToolTipText("Busca Cidade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cidade.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Numero:");

        numero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numero.setNumeroCasa(0);
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Telefone:");

        telefone.setMascara("0(##)####-#####");
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("E-mail:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Bairro:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Rua:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("CEP:");

        complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("RG:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Celular:");

        celular.setMascara("0(##)####-#####");
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Site:");

        site.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siteActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Empresa:");

        empresa.setPesquisavel(java.lang.Boolean.TRUE);

        javax.swing.GroupLayout infCompPainelLayout = new javax.swing.GroupLayout(infCompPainel);
        infCompPainel.setLayout(infCompPainelLayout);
        infCompPainelLayout.setHorizontalGroup(
            infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infCompPainelLayout.createSequentialGroup()
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infCompPainelLayout.createSequentialGroup()
                        .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infCompPainelLayout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infCompPainelLayout.createSequentialGroup()
                                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(infCompPainelLayout.createSequentialGroup()
                                        .addComponent(complemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel11))
                                    .addGroup(infCompPainelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel13))
                                    .addGroup(infCompPainelLayout.createSequentialGroup()
                                        .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(site, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(rg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(infCompPainelLayout.createSequentialGroup()
                        .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(infCompPainelLayout.createSequentialGroup()
                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        infCompPainelLayout.setVerticalGroup(
            infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infCompPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infCompPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabPainel.addTab("Informações Complementares", infCompPainel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fornecedorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fornecedorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPainel))
        );

        jpane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpaneLayout = new javax.swing.GroupLayout(jpane);
        jpane.setLayout(jpaneLayout);
        jpaneLayout.setHorizontalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLAbel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaneLayout.setVerticalGroup(
            jpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(messageLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hFComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFComboBox1FocusLost

    }//GEN-LAST:event_hFComboBox1FocusLost

    private void hFComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hFComboBox1ActionPerformed

    }//GEN-LAST:event_hFComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void cepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepFocusLost
        log = listner.buscaLogradouroCep(new BeanEvent(this, cep.getValorBigint()));
        if (log != null) {
            cidade.setText(log.getIdcidade().getSigla() + " - " + log.getDescricao());
            cep.setValorComZerosLPAD(log.getCep(), 8);
        } else {
            cidade.setText("");
            cep.limpar();
        }
    }//GEN-LAST:event_cepFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listner.buscaCep(new BeanEvent(this, null));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementoActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void siteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siteActionPerformed

    private void listaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFornecedoresMouseClicked
        if (evt.getClickCount() == 2) {
            if (listaFornecedores.getSelectedRowCount() > -1) {
                HefFornecedorInfo info = (HefFornecedorInfo) listaFornecedores.getValorColunaDaLinhaSelecionada(OBJ);
                montaFornecedor(info);
                fornecedorPanel1.montaFornecedor(info);
            }
        }
    }//GEN-LAST:event_listaFornecedoresMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField bairro;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField celular;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField cep;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField cidade;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField complemento;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField email;
    private com.hefesto.hefestocomponentes.HFComboBox.HFComboBox empresa;
    private com.hefesto.hefestocliente.core.componentes.FornecedorPanel fornecedorPanel1;
    private javax.swing.JPanel fornecedoresCadastradosPanel;
    private javax.swing.JPanel infCompPainel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpane;
    private com.hefesto.hefestocomponentes.HFTable.HFTable listaFornecedores;
    private com.hefesto.hefestocomponentes.HFLabel.HFLabel messageLAbel;
    private com.hefesto.hefestocomponentes.HFNumberField.HFNumberField numero;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField rg;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField rua;
    private com.hefesto.hefestocomponentes.HFTextField.HFTextField site;
    private javax.swing.JTabbedPane tabPainel;
    private com.hefesto.hefestocomponentes.HFFormattedTextField.HFFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables

    @Override
    public void novo() {
        Limpar();
    }

    @Override
    public void Limpar() {
        super.Limpar();
        fornecedorPanel1.limpar();
        tabPainel.setSelectedComponent(fornecedoresCadastradosPanel);
        carregar(new BeanEvent(this, null));
    }

    @Override
    public void salvar() {
        HefFornecedorInfo info = fornecedorPanel1.getFornecedor();
        if (info != null) {
            if (empresa.valida() && cep.Valida()
                    && rua.Valida() && numero.Valida()
                    && bairro.Valida() && telefone.Valida()) {
                info.setBairro(bairro.getText());
                info.setCelular(celular.getValorBigint());
                info.setComplemento(complemento.getText());
                info.setEmail(email.getText());
                info.setIdempresa((HefEmpresa) empresa.getObjetoSelecionado());
                info.setIdlogradouro(log);
                info.setNumero(numero.getBigIntValor());
                info.setNurg(rg.getValorString());
                info.setRua(rua.getText());
                info.setSite(site.getText());
                info.setTelefone(telefone.getValorBigint());

                salvar(new BeanEvent(this, info));

            }

        }

    }

    private void montaFornecedor(HefFornecedorInfo info) {
        if (info.getIdfornecedorInfo() != null) {
            tabPainel.setSelectedComponent(infCompPainel);
            empresa.setObjetoSelecionado(info.getIdempresa());
            cep.setValor(info.getIdlogradouro().getCep());
            cidade.setText(info.getIdlogradouro().getDescricao() + " - " + info.getIdlogradouro().getIdcidade().getDescricao());
            rua.setText(info.getRua());
            bairro.setText(info.getBairro());
            numero.setText(info.getNumero() + "");
            complemento.setText(info.getComplemento());
            email.setText(info.getEmail());
            rg.setValor(info.getNurg());
            site.setText(info.getSite());
            telefone.setValor(info.getTelefone());
            celular.setValor(info.getCelular());
            log = info.getIdlogradouro();
        }

    }

    public void montaTabelaFornecedor(List<?> lst) {
        listaFornecedores.removeTable();
        listaFornecedores.addListRows(lst);
    }

    @Override
    public void update(java.util.Observable o, Object arg) {
        if (arg instanceof HefFornecedorInfo) {
            montaFornecedor((HefFornecedorInfo) arg);
        } else if (arg instanceof HefLogradouro) {
            log = (HefLogradouro) arg;
            cidade.setText(log.getIdcidade().getSigla() + " - " + log.getDescricao());
            cep.setValorComZerosLPAD(log.getCep(), 8);
        }
    }

    public void montaComboEmpresa(List<?> montaComboEmpresa) {
        empresa.adicionarItens(montaComboEmpresa);
    }

}
